name: pro_shoywon_editing_zone
description: A premium photo editing application built for free.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image: ^4.1.3
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
